name 'consul-vault'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures consul-vault'
long_description 'Installs/Configures consul-vault'
version '0.1.0'
